config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :teams do
    resources :tasks
  end

  root 'pages#index'
  get '/teams/:id/join' => 'teams#join', as: :join_team

  put '/tasks/:id/change' => 'tasks#change'

  get '/contact' => 'pages#contact', as: :contact
  get '/about' => 'pages#about', as: :about

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :team

  validates :name, presence: true
  validates :description, presence: true

  def part_of?(team)
    team.tasks.include?(self)
  end
end

app/models/team.rb
class Team < ActiveRecord::Base
  has_many :users
  has_many :tasks, dependent: :destroy
  validates :name, presence: true

  def has_user?(user)
    user.team == self
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :team
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if current_user
      if current_user.team
        redirect_to team_path current_user.team
      end
    end
  end

  def about
  end

  def contact
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user!
  before_action :correct_team, only: [:edit, :show, :update]

  def new
    @team = current_team
    @task = @team.tasks.build
  end

  def create
    @task = Task.new(task_params)
    @task.team_id = current_user.team.id
    @task.category = 'C1'
    if @task.save
      flash[:success] = 'Task created!'
      redirect_to team_path(current_team)
    else
      flash[:danger] = 'Task not saved'
      render 'new'
    end
  end

  def edit
    @team = current_team
  end

  def change
    @task = Task.find(params[:id])
    @task.update_attributes(category: params[:category])
    respond_to do |format|
      format.js
    end
  end

  def update
    if @task.update_attributes(task_params)
      flash[:success] = 'Task updated'
      redirect_to team_task_path(current_team,@task)
    else
      flash[:danger] = 'Error'
      redirect_to root_path
    end
  end

  def show
  end

  def index
    @tasks = Task.where(team_id: current_team.id)
  end

  private

  def task_params
    params.require(:task).permit(:name, :description)
  end

  def correct_team
    @task = Task.find(params[:id])
    unless @task.part_of?(current_user.team)
      flash[:danger] = 'This is not your teams task'
      redirect_to root_path
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:show, :edit, :update]

  def new
    if current_user.team
      flash[:danger] = 'You already belong to a team'
      redirect_to root_path
    else
      @team = Team.new
    end
  end

  def create
    @team = Team.new(team_params)
    @team.users << current_user
    if @team.save
      flash[:success] = "#{@team.name} team created"
      redirect_to @team
    else
      flash[:danger] = 'Team not created'
      render 'new'
    end
  end

  def show
    @tasksc1 = Task.where(team_id: @team.id, category: 'C1')
    @tasksc2 = Task.where(team_id: @team.id, category: 'C2')
    @tasksc3 = Task.where(team_id: @team.id, category: 'C3')
    @tasksc4 = Task.where(team_id: @team.id, category: 'C4')
  end

  def edit
  end

  def update
    if @team.update_attributes(team_params)
      flash[:success] = "Team #{@team.name} edited"
      redirect_to @team
    else
      flash[:danger] = 'Team not edited'
      render 'edit'
    end
  end

  def index
    @teams = Team.all
  end

  def join
    current_user.team = Team.find(params[:id])
    current_user.save
    redirect_to team_path current_user.team
  end

  private

  def team_params
    params.require(:team).permit(:name)
  end

  def correct_user
    @team = Team.find(params[:id])
    unless @team.has_user?(current_user)
      flash[:danger] = 'This is not your team'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_team
    return current_user.team if current_user
  end
end

app/helpers/pages_helper.rb
module PagesHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Kanban', root_path, class: "navbar-brand" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navi">
        <% if current_user && current_user.team %>
          <li><%= link_to current_team.name, current_team %></li>
          <li><%= link_to 'Add task', new_team_task_path(current_team) %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right navi">
        <li><%= link_to 'About', about_path %></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <% if current_user %>
        <li><%= link_to current_user.email, edit_user_registration_path(current_user) %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: 'delete' %></li>
        <% else %>
        <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for?(:title) ? yield(:title) : "Kanban" %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
      <% end %>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/_register.html.erb
<h2>Sign up</h2>

<%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
  <%= devise_error_messages! %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @validatable %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="actions">
    <%= f.submit "Sign up" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/pages/about.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-offset-3 col-md-6">
      <p class="about">Kanban is a system that was used in 1940s to optimize Toyota engineering process. With minor changes it can be applied to software development. The key idea behind Kanban is to optimize the flow between amount of work in progress and teams capacity to perform work. Read more about Kanban <%= link_to 'here', 'https://www.atlassian.com/agile/kanban' %>.</p>
    </div>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-offset-3 col-md-6">
      <h3>Hey it's great having you here! My name is Adam and I created this app. Feel free to contact me here:</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-4 col-lg-offset-3 col-lg-2 social">
      <a href="https://twitter.com/ASzczombrowski"><span class="fa fa-twitter"></span>twitter</a>
    </div>
    <div class="col-sm-4 col-lg-2 social">
      <a href="https://github.com/adam-szczombrowski"><span class="fa fa-github"></span>github</a>
    </div>
    <div class="col-sm-4 col-lg-2 social">
      <a href="https://www.linkedin.com/in/adam-szczombrowski-94111465?trk=hp-identity-photo"><span class="fa fa-linkedin"></span>linkedIn</a>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-offset-3 col-md-6">
      <h3>Or write me an email: adam.szczombrowski@gmail.com</h3>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-offset-4 col-md-4 central">
      <% if current_user %>
        <h1><%= link_to 'Join the existing team', teams_path %></h1> or <h1> <%= link_to 'Create a team', new_team_path %> </h1>
      <% else %>
        <h1>Join Kanban today!</h1>
        <p>Kanban is super easy tool to boost your productivity with Kanban method. Find more by signing in below!</p>
        <%= render 'register' %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/_task.html.erb
<div class="task" id=<%= task.id %> >
<p><%= link_to task.name, team_task_path(task.team, task) %></p>
<p><%= task.description %></p>
</div>

app/views/tasks/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-offset-3 col-md-6 central">
      <h1>Edit task</h1>
      <%= bootstrap_form_for [@team, @task] do |f| %>
        <%= f.text_field :name %>
        <%= f.text_area :description %>
        <%= f.submit "Edit" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<% @tasks.each do |t| %>
  <%= t.name %>
<% end %>

app/views/tasks/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-offset-3 col-md-6 central">
      <h1>Create task</h1>
      <%= bootstrap_form_for [@team, @task] do |f| %>
        <%= f.text_field :name %>
        <%= f.text_area :description %>
        <%= f.submit "Add task" %>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-12 col-md-offset-3 col-md-6 central">
      <%= render @task %>
      <%= link_to 'Edit task', edit_team_task_path(current_team, @task), class: 'btn btn-default' %>
    </div>
  </div>
</div>